version: "3.8"

services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports: 
      - "3000:3000"
    depends_on:
      - nodeserver

  nodeserver:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
   
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - ./data:/data/db
